import 'bootstrap/dist/css/bootstrap.min.css'
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import Header from '@/components/Header';

const openSans = Open_Sans({ 
  subsets: ['latin'], 
  weight: ['400', '500', '600', '700', '800'] 
});

export const metadata: Metadata = {
  title: "Purwadhika Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        <main>
          {children}
        </main>
        <Script src='/assets/js/bootstrap.bundle.min.js'></Script>
      </body>
    </html>
  );
}
